spring:
#  profiles:
#    active: datasource-single
  datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password:
        url: jdbc:mysql://localhost:3306/my?characterEncoding=utf-8
        type: com.alibaba.druid.pool.DruidDataSource
      # Druid 自定义配置，对应 DruidDataSource 中的 setting 方法的属性
        druid:
          driver-class-name: com.mysql.cj.jdbc.Driver
          username: root
          password:
          url: jdbc:mysql://localhost:3306/my?characterEncoding=utf-8
          test-on-borrow: true
          filters: stat,wall,slf4j   # 配置 项目已经配置的日志模式 才能生效记录
          #          type: com.alibaba.druid.pool.DruidDataSource
          min-idle: 0 # 池中维护的最小空闲连接数，默认为 0 个。
          max-active: 50 # 池中最大连接数，包括闲置和使用中的连接，默认为 8 个。
          filter:
            stat: # 配置 StatFilter ，对应文档 https://github.com/alibaba/druid/wiki/%E9%85%8D%E7%BD%AE_StatFilter
              log-slow-sql: true # 开启慢查询记录
              slow-sql-millis: 5000 # 慢 SQL 的标准，单位：毫秒
          stat-view-servlet: # 配置 StatViewServlet ，对应文档 https://github.com/alibaba/druid/wiki/%E9%85%8D%E7%BD%AE_StatViewServlet%E9%85%8D%E7%BD%AE
            enabled: true # 是否开启 StatViewServlet
            login-username: admin # 账号
            login-password: admin # 密码

jwt:
  header: "Authorization" #token返回头部
  tokenPrefix: "Bearer " #token前缀
  secret: "qwertyuiop7418520" #密钥
  expireTime: 100 #token有效时间 (分钟) 建议一小时以上